### ISSUE TITLE
Any install instructions?

### ISSUE THREAD

**Issue by bh016088** [kismatic/kubernetes-ldap#5]
I can't find any instructions on how to use this.  Any README or implementation instructions?

**Comment by mdgreenfield** [comment]
:+1:

**Comment by mkumatag** [comment]
Anything latest on this? Can you please point to some wiki/doc to setup ldap for k8s.?

**Comment by preillyme** [comment]
@alexbrand — Can you help @mkumatag @mdgreenfield and @bh016088 with this?

**Comment by alexbrand** [comment]
Absolutely.

@mkumatag @mdgreenfield @bh016088 we have updated the readme with information on how to configure the plugin with Kubernetes 1.3. Let me know if you run into any issues.

**Comment by mkumatag** [comment]
Instructions mentioned are good enough to try. Thanks a lot.

**Comment by bh016088** [comment]
Closing!  Thanks!
